### ISSUE TITLE
Issue in ml_scikitlearn_decision_tree_classification_simple.py

### ISSUE THREAD

**Issue by gandhirajan** [rishal-hurbans/Grokking-Artificial-Intelligence-Algorithms#6]
Getting following error while executing ml_scikitlearn_decision_tree_classification_simple.py :

Traceback (most recent call last):
  File "ml_scikitlearn_decision_tree_classification_simple.py", line 54, in <module>
    graph.write_png('tree.png')
  File "C:\Installers\Python\Python37\lib\site-packages\pydotplus\graphviz.py", line 1810, in <lambda>
    prog=self.prog: self.write(path, format=f, prog=prog)
  File "C:\Installers\Python\Python37\lib\site-packages\pydotplus\graphviz.py", line 1918, in write
    fobj.write(self.create(prog, format))
  File "C:\Installers\Python\Python37\lib\site-packages\pydotplus\graphviz.py", line 1960, in create
    'GraphViz\'s executables not found')
pydotplus.graphviz.InvocationException: GraphViz's executables not found

**Comment by rishal-hurbans** [comment]
Thanks for raising this. I've added graphviz to the requirements.txt. You can also use `pip3 install graphviz` to install the required dependency.

**Comment by gandhirajan** [comment]
@rishal-hurbans Did pip3 install graphviz and still facing the same issue. I m using windows10 and python 3.7.0 Also please note that the requirements.txt is not getting executed with the latest version of Python.
